name: tests

on: 
  push:
      branches:
          - main

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.3']
  
    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          coverage: none
          tools: composer, phpunit:10.5
          #ini-values: "memory_limit=512M"

      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install OpenBLAS
        run: |
          sudo apt install -y libopenblas-base liblapacke
          wget https://github.com/rindow/rindow-openblas/releases/download/0.4.0/rindow-openblas-php8.3_0.4.0-1+ubuntu22.04_amd64.deb
          sudo apt install -y ./rindow-openblas-php8.3_0.4.0-1+ubuntu22.04_amd64.deb

      #- name: Install OpenCL
      #  run: |
      #    sudo apt install -y clinfo
      #    sudo apt install -y pocl-opencl-icd
      #    sh clblast-packdeb.sh
      #    sudo apt install ./clblast_1.6.2-1+ubuntu22.04_amd64.deb
      #    wget https://github.com/rindow/rindow-opencl/releases/download/0.2.0/rindow-opencl-php8.3_0.2.0-1+ubuntu22.04_amd64.deb
      #    sudo apt install -y ./rindow-opencl-php8.3_0.2.0-1+ubuntu22.04_amd64.deb
      #    wget https://github.com/rindow/rindow-clblast/releases/download/0.2.0/rindow-clblast-php8.3_0.2.0-1+ubuntu22.04_amd64.deb
      #    sudo apt install -y ./rindow-clblast-php8.3_0.2.0-1+ubuntu22.04_amd64.deb

      #- name: Composer
      #  uses: php-actions/composer@v6
      #  with:
      #    php_version: ${{ matrix.php }}
      
      - name: Composer
        run: composer update

      #- name: PHPUnit Tests
      #  uses: php-actions/phpunit@v3
      #  with:
      #    configuration: tests/phpunit.xml
      #    version: 10.5
      #    php_version: ${{ matrix.php }}
      #    filter: ReleaseTest

      - name: PHPUnit Tests.
        run: phpunit -c tests
